id: I9CA8ED18
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T03:59:24+00:00'
last_modified: '2022-06-08T11:03:07.202107+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG21821
  title: པཎ་ཆེན་སྣང་བ་མཐའ་ཡས་མཆོག་གི་མཛད་འཕྲིན་ཆེ་ལོང་ཙམ་ཞིག་གི་རྟོགས་བརྗོད་དད་པའི་ས་བོན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    9AB7:
      image_group_id: I1KG21901
      title: ''
      total_pages: 90
      order: 1
      base_file: 9AB7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
