id: P009440
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG21821
  title: པཎ་ཆེན་སྣང་བ་མཐའ་ཡས་མཆོག་གི་མཛད་འཕྲིན་ཆེ་ལོང་ཙམ་ཞིག་གི་རྟོགས་བརྗོད་དད་པའི་ས་བོན།
  author: ''
  volumes:
    c16121272049461aa48cea2b59bd06e1:
      image_group_id: I1KG21901
      title: ''
      volume_number: 1
      total_pages: 90
